BoxLayout:
    orientation: 'vertical'
    BoxLayout:
        TextInput:
            id: input_number
            text: '7'
            font_size: 48
            multiline: False
        Button:
            text: 'Square'
            on_press: app.handle_calculate(int(input_number.text))
        Label:
            id: output_label
            font_size: 48
            color: (255, 0, 255, 1)
    BoxLayout:
        Label:
            text: 'Enter a number and press "Square"'
